name: samawa
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.1
  intl: ^0.15.8
  hijri: ^2.0.2
  geocoder: ^0.2.1
  shared_preferences: any
  geolocator: ^5.3.2+2
  sqflite: any
  path_provider: any
  flutter_local_notifications: ^1.4.2
  rxdart: ^0.23.1
  flutter_automation: any
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  intro_slider: ^2.2.8
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo212.png 
    - assets/images/bg.png
    - assets/images/bg1.png
    - assets/images/bg2.png
    - assets/images/bgNight.png
    - assets/images/bgEvening.png
    - assets/images/bgNoon.png
    - assets/images/intro_adzan.png
    - assets/images/intro_quran.png
    - assets/images/intro_doa.png
    - assets/images/woman0.png
    - assets/images/woman1.png
    - assets/images/woman2.png
    - assets/images/woman3.png
    - assets/images/man0.png
    - assets/images/man1.png
    - assets/images/man2.png
    - assets/images/man3.png
    - assets/images/rectColor.png
    - assets/images/quran.png
    - assets/images/doa.png
    - assets/images/sun.png
    - assets/images/sun1.png
    - assets/images/moon.png


  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/AvenirLTStd-Roman.otf

    - family: AvenirPro
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
          weight: 400
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 700
         
  
